### ISSUE TITLE
Make labels for the remote resources equal local ones

### ISSUE THREAD

**Issue by qurname2** [ytsaurus/ytsaurus-k8s-operator#381]
Right now when one creates remoteData/Tablet/Exec nodes, the new statefulset has incorrect map of labels, specifically
**ytsaurus.tech/cluster-name** and **app.kubernetes.io/part-of**.
Examples:
local dataNode:
```
labels:
    app.kubernetes.io/component: yt-data-node-dn-rack1
    app.kubernetes.io/managed-by: ytsaurus-k8s-operator
    app.kubernetes.io/name: yt-data-node
    app.kubernetes.io/part-of: yt-clusterA
    yt_component: clusterA-yt-data-node-dn-rack1
    ytsaurus.tech/cluster-name: clusterA
```

remoteDataNode in the same cluster:
```
labels:
    app.kubernetes.io/component: yt-data-node-r-rack2
    app.kubernetes.io/managed-by: ytsaurus-k8s-operator
    app.kubernetes.io/name: yt-data-node
    app.kubernetes.io/part-of: yt-remote-data-node-clusterA-rack2
    yt_component: remote-data-node-clusterA-rack2-yt-data-node-r-rack2
    ytsaurus.tech/cluster-name: remote-data-node-clusterA-rack2
```
